apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-backend
  template:
    metadata:
      labels:
        app: devops-backend
    spec:
      containers:
        - name: devops-backend
          image: devops-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
