apiVersion: v1
kind: Service
metadata:
  name: devops-backend-service
spec:
  type: NodePort
  selector:
    app: devops-backend
  ports:
    - port: 8081        # port exposé à l'intérieur du cluster
      targetPort: 8081  # port du conteneur
      nodePort: 30007   # port accessible depuis l’extérieur
